apiVersion: v1
kind: ReplicationController
metadata:
  name: myonlinestore-rc  
spec:
  replicas: 2
  selector:
    app: myonlinestore
  template:
    metadata:
      labels:
        app: myonlinestore
    spec:
      containers:
      - name: myonlinestore-container
        image: maha4iac/mahaonlinestore:2
        ports:
        - containerPort: 8080